name: Node CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Checking code lint
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm ci
          npm run lint --if-present && echo 'Code lint OK!'
        env:
          CI: "true"
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [8.x, 10.x, 12.x]

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: npm install, build, and test
  #       run: |
  #         npm ci
  #         npm run lint --if-present && echo 'Code lint OK!'
  #         npm run build --if-present
  #         npm test
  #       env:
  #         CI: "true"
